### ISSUE TITLE
mozjpeg build horribly slowing down the mobile CI

### ISSUE THREAD

**Issue by ajayindfw** [imagemin/mozjpeg-bin#12] opened 2015-12-07 03:57 UTC
As part of our iOS and Android builds for a hybrid mobile application built using JS, HTML5 and CSS, we are using npm install to install our dependencies. One of the dependency "ionic-minify" through a series of dependencies and transitive dependencies calls "mozjpeg@4.0.1 install which then calls:

mozjpeg@4.0.1 postinstall //node_modules/mozjpeg 
node lib/install.js

This step takes forever (almost 30-40 minutes) to finish on a Mac Mini where we are running a ci server to automatically build iOS and Android mobile packages. I have tried increasing the verbose level of npm log in an attempt to find the source of the problem but unfortunately the logging verbosity level only applies to the direct dependencies specified in my application packages.json and does not provide verbose logging information when the first level dependencies do "npm install" on their dependencies as part of the build of our application.

Please help.

**Comment by shinnn** [comment] 2015-12-07 05:06
Please tell us:

* OS version
* Node version
* npm version

**Comment by ajayindfw** [comment] 2015-12-07 07:42
node: 0.12.7
npm: 2.11.3
OS: Darwin (Mac Mini)

**Comment by shinnn** [comment] 2015-12-07 07:47
> OS
> # version

**Comment by ajayindfw** [comment] 2015-12-07 07:49
Darwin 14.1.0 (Kernel version)

**Comment by shinnn** [comment] 2015-12-07 08:24
```
$ sw_vers
```

**Comment by ajayindfw** [comment] 2015-12-07 12:37
ProductName: Mac OS X
ProductVersion: 10.10.2
BuildVersion: 14C109

**Comment by shinnn** [comment] 2015-12-07 12:38
@ajayindfw Can you try again after updating Node and npm to their latest stable versions?

**Comment by ajayindfw** [comment] 2015-12-08 08:44
I upgraded node to 0.12.9 and npm to 3.5.1 and the build is still running slow as before.  I don't think it is related to the npm and node versions though the upgrade was important for other reasons.

**Comment by shinnn** [comment] 2015-12-08 12:27
> This step takes forever (almost 30-40 minutes) to finish on a Mac Mini

Does the installation finally succeed, or fail by timeout?

**Comment by ajayindfw** [comment] 2015-12-08 18:20
It still takes forever.  Did not help with the performance issue.

**Comment by shinnn** [comment] 2015-12-08 18:29
Show us a small Github repository that can reproduce the problem. [Travis CI has the OS X Build Environment](https://docs.travis-ci.com/user/osx-ci-environment/) and we can see whether mozjpeg-bin is the root cause or not.

**Comment by shinnn** [comment] 2015-12-08 18:38
https://github.com/imagemin/mozjpeg-bin/issues/12#issuecomment-162815148

> I upgraded node to 0.12.9

https://github.com/imagemin/mozjpeg-bin/issues/12#issuecomment-162512868

> try again after updating Node and npm to their **latest stable** versions

**Comment by ajayindfw** [comment] 2015-12-08 18:43
i did both the upgrades and it still runs slow.

**Comment by shinnn** [comment] 2015-12-08 18:43
https://github.com/imagemin/mozjpeg-bin/issues/12#issuecomment-162971244

**Comment by shinnn** [comment] 2015-12-08 18:45
> i did both

The latest stable Node is v5.1.1, not v0.12.9.

**Comment by ajayindfw** [comment] 2015-12-08 18:46
What is the main difference between v5.1.1 and 0.12.9. That's a massive
upgrade.

**Comment by shinnn** [comment] 2015-12-08 18:49
> the main difference

[ES2015](https://github.com/lukehoban/es6features#readme)

Also some problems related to imagemin project are fixed in v5.x. https://github.com/imagemin/imagemin/issues/133#issuecomment-152750841

**Comment by ajayindfw** [comment] 2015-12-08 18:56
Sorry, I cannot upgrade to node 5.x. We have a very tight corporate policy
on the upgrades. I did not mind the previous upgrade as it was a logical
upgrade. I am not sure why an upgrade is required to reproduce the issue.

**Comment by shinnn** [comment] 2015-12-08 19:05
OK, OK. So,

1. Create a small Github repository that can reproduce the problem on your machine.
2. Build it on [Travis CI](https://travis-ci.org/) in [OS X mode](https://docs.travis-ci.com/user/osx-ci-environment/) and show us the result. I want to check whether this library is the root cause or not.

If the problem doesn't occur on Travis CI, this is just an issue with your machine, network other programs.

**Comment by shinnn** [comment] 2015-12-14 13:32
No feedback.

**Closed by shinnn** 2015-12-14 13:32 UTC
